# Generated by Django 3.2.9 on 2022-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_question_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_char',
            field=models.CharField(default='A', max_length=20),
        ),
    ]
